### ISSUE TITLE
Installation - Inno Setup Compiler + AppBundle + Github Action

### ISSUE THREAD

**Issue by ricaun** [chuongmep/RevitAddInManager#1]
Hello!

A long time ago I created this repo with the close source AddinManager.dll.
* https://github.com/ricaun/RevitAddInManagerCollection

The idea is the same, compile the necessary files to create an `AddinManager.bundle` and create an `Inno` file to create an executable.

The past month I create the [ricaun.Nuke.PackageBuilder](https://github.com/ricaun-io/ricaun.Nuke.PackageBuilder) to do exactly that using the [Nuke Build](https://nuke.build/)

The Github Action Release the Executable file.

Check my repo: https://github.com/ricaun/RevitAddInManager

Still need to add the base images for the installer and a simple license then I gonna create a PR.

See yaa

**Comment by chuongmep** [comment]
wow, many thanks ricaun, let me check first in branch dev.Awesome, i'm not a designer but if you need, can i get more info on the required image size?

**Comment by ricaun** [comment]
Here have a sample of the Images. https://github.com/ricaun-io/ricaun.Nuke.PackageBuilder/tree/master/RevitAddin.PackageBuilder.Example/InstallationFiles

* icon.ico - 32x32
* image.bmp - 55x55
* imageSmall.bmp - 164x314

**Comment by chuongmep** [comment]
I thinking of extending the setting to **msi** to support the auto install for business maybe i am considering with **wix sharp**, do we have a cross auto solution ?

**Comment by ricaun** [comment]
What is the advantage to use MSI? What do you mean auto-install for business?

I know the [RevitTemplates](https://github.com/Nice3point/RevitTemplates/tree/main/Templates/Nice3point.Revit.Solution) has some WixSharp solutions.

**Comment by chuongmep** [comment]
msi has advantages in custom modification or changing file information as needed or fixing errors , they are many advantages over exe which i have done before, luckily i found revitlookup did that too.

**Comment by ricaun** [comment]
The code creates the exe file using the [Inno Setup](http://www.jrsoftware.org/isinfo.php) I never had a problem with this installer.

At the time I suggest on Revitlookup to use Inno but was discard, I didn't have a automation process to create the installation direct on Guihub. 

I could add this possiblity on [PackageBuilder](https://github.com/ricaun-io/ricaun.Nuke.PackageBuilder) to use a Wixsharp project to create the installation.

**Comment by chuongmep** [comment]
Awesome, for now i will apply the setting with the exe first, then improve later with your updates, thanks a lot.
The images I will give the design team to work on and send back to you

**Comment by chuongmep** [comment]
Hi @ricaun, I updated installer with msi, you can check, me be i will close this topic.Thanks you.

**Comment by chuongmep** [comment]
I will add some things that msi is very convenient like:
- Repair File
![image](https://user-images.githubusercontent.com/31106432/150573211-182d02b9-3a60-4c4b-8ca9-be8ecae8de54.png)
- Edit custom to install in azure or check file assembly 
![image](https://user-images.githubusercontent.com/31106432/150573452-cd8e130c-1489-4ef0-b378-78b34471f9da.png)
