### ISSUE TITLE
Viewmodel objects are not cached

### ISSUE THREAD

**Issue by Nice3point** [chuongmep/RevitAddInManager#11]
https://github.com/chuongmep/RevitAddInManager/blob/8faa9fff26524c74eb5aadeb4e6bf3ae115c69cd/AddInManager/ViewModel/AddInManagerViewModel.cs#L105

Caching variant:
```c#
public RelayCommand ExecuteAddinCommand => _executeAddinCommand ??= new RelayCommand(ExecuteAddinCommandClick);
```

this will reduce memory consumption

**Comment by chuongmep** [comment]
@Nice3point  you have any document suggesst about this ?

**Comment by Nice3point** [comment]
no, it's just that every time you access a property, a new object is created for which memory is allocated, instead it's better to reuse the previous one

**Comment by Nice3point** [comment]
From literature, maybe this book https://t.me/programmist_of/210

**Comment by chuongmep** [comment]
Problem resoleved
