### ISSUE TITLE
Correct usage of INotifyPropertyChanged

### ISSUE THREAD

**Issue by Nice3point** [chuongmep/RevitAddInManager#12]
https://github.com/chuongmep/RevitAddInManager/blob/8faa9fff26524c74eb5aadeb4e6bf3ae115c69cd/AddInManager/ViewModel/AddInManagerViewModel.cs#L36

The INotifyPropertyChanged interface provides a method: `private void OnPropertyChanged([CallerMemberName] string propertyName = null)`

Here is the correct use case for property with notification:
```c#
public string CommandItems  
{
    get => _commandItems;
    set
    {
        if (value == _commandItems) return;
        _commandItems = value;
        OnPropertyChanged();
    }
}
```

Using ref and other overloads is superfluous.

**Comment by chuongmep** [comment]
Many thanks @Nice3point, fixed include application
