### ISSUE TITLE
Milti version config

### ISSUE THREAD

**Issue by Nice3point** [chuongmep/RevitAddInManager#13]
https://github.com/chuongmep/RevitAddInManager/blob/8faa9fff26524c74eb5aadeb4e6bf3ae115c69cd/AddInManager/RevitAddinManager.csproj#L34

The project only compiles under the 2022 version of Revit, the Readme says support until 2014, you need to add the solution and project configurations for this:
https://github.com/Nice3point/RevitTemplates/blob/main/Templates/Nice3point.Revit.AddIn/Nice3point.Revit.AddIn.csproj
https://github.com/Nice3point/RevitTemplates/wiki/Multiple-Revit-Versions

**Comment by Nice3point** [comment]
you added project configs 19 to 22 but solution config is still set to 22

**Comment by Nice3point** [comment]
https://github.com/chuongmep/RevitAddInManager/blob/ad5e60ed2995f8c81ad807e3e2e8b1ffad4afcd5/AddInManager/RevitAddinManager.csproj#L10

this property should not be at the beginning, and the libraries version is still 2022)

**Comment by chuongmep** [comment]
@Nice3point  may be have problem when we use some number after to build version
![image](https://user-images.githubusercontent.com/31106432/151187305-4b414d51-c91f-4ac9-9b97-88775c9ba489.png)

**Comment by Nice3point** [comment]
move this line below like here
https://github.com/Nice3point/RevitTemplates/blob/main/Templates/Nice3point.Revit.AddIn/Nice3point.Revit.AddIn.csproj#L38

**Comment by Nice3point** [comment]
And for the Nuget package, the version number changes to this:
`<PackageReference Include="Revit_All_Main_Versions_API_x64" Version="$(RevitVersion).*" />`

**Comment by Nice3point** [comment]
Nuke will build a dll for each such solution configuration, and then this file will not be needed https://github.com/chuongmep/RevitAddInManager/blob/dev/Installer/BuildVersions.cs

**Comment by Nice3point** [comment]
You can still use the Revit_All_Main_Versions_API_x64 library, you don't have to change it at all 😉

**Comment by Nice3point** [comment]
Example Solution Configurations 
https://github.com/Nice3point/RevitTemplates/blob/main/Templates/Nice3point.Revit.Solution/Nice3point.Revit.Solution.sln#L23

**Comment by chuongmep** [comment]
hmm. Let me check fist with that, 
![image](https://user-images.githubusercontent.com/31106432/151189358-f2152325-4e06-49e3-b334-f8abd89df7f2.png)

**Comment by Nice3point** [comment]
![изображение](https://user-images.githubusercontent.com/20504884/151189007-c6652037-0bf8-439c-9635-25e5a37342c7.png)
When you set up the configurations correctly, Nuke for all Release configurations will compile the project and add the assembly to the installer, only you will need to use the code from the templates, the RevitLookup project has a heavily truncated and changed code

**Comment by Nice3point** [comment]
Debug configurations can only be created for the 22nd version, I don’t think that this project will have a lot of API dependent code

**Comment by chuongmep** [comment]
Only revit api x64 dependent in project, i has remove some library wpf no need yesterday

**Comment by Nice3point** [comment]
@chuongmep   `/p:Configuration=Installer` 
Turn off building the AddInManager project for this solution configuration

**Comment by Nice3point** [comment]
you can leave it as it is for now, I'll do everything in 2 hours and send a PR

**Comment by chuongmep** [comment]
many thanks @Nice3point , I'm still very new to nuke, hope you can help !
