### ISSUE TITLE
Use Add-in Manager without loading a model. 

### ISSUE THREAD

**Issue by StephenDini** [chuongmep/RevitAddInManager#28]
**Is your feature request related to a problem? Please describe.**
I would like to be able to run add-ins without a model running. My goal is to automate the Navisworks exports and to do this I need to test this apps execution on a newly opened Revit application.  

**Describe the solution you'd like**
Allow the button to work without a model opened. 

**Describe alternatives you've considered**
While this has more features and I will use it for future development,  for the moment i will stick to the official one for this current task. 

**Additional context**
![image](https://user-images.githubusercontent.com/38794144/176438087-c30b7d4e-a585-4e80-8b80-60339e2b93a5.png)

**Comment by chuongmep** [comment]
Many thanks reported, problem will be fix in version 1.3.5 now.
