### ISSUE TITLE
File load is invalid

### ISSUE THREAD

**Issue by a-littlecat** [chuongmep/RevitAddInManager#29]
**Describe the bug**
Load DLL file display “File load is invalid”

**To Reproduce**

**Expected behavior**
Click to load the selected file, and this prompt box will appear.
DLL file address is"D:\03 其他\C#\revit\re_s_02\re_s_02\bin\Debug\net6.0\re_s_02.dll"

**Screenshots**
![image](https://user-images.githubusercontent.com/25222054/179687583-b644ecb7-2c3f-4c82-92ec-d079ca42c8a2.png)

**Desktop (please complete the following information):**
win10 21H2
VS2022 
.net 6.0
revit2020

**Comment by chuongmep** [comment]
Dear @a-littlecat, Revit not support dll build use NET6 origin now, only use .NET6 for apply Style SDK and select target framework is NET 4.8.
https://github.com/chuongmep/RevitAddInManager/blob/9c3cc0fbd80acffcd2c7ad65f3045fc4d2404744/AddInManager/RevitAddinManager.csproj#L8

**Comment by a-littlecat** [comment]
Thank you for replying to this silly question. It has been solved. Because I just started, I don't understand a lot.￣▽￣@chuongmep

**Comment by chuongmep** [comment]
Nice, i will close this issue.
