### ISSUE TITLE
Testing debug with a modeless form not working?

### ISSUE THREAD

**Issue by pierrenavarra** [chuongmep/RevitAddInManager#30]
Hi @chuongmep 

I've got an other pb with my solution and debugging with AIM.
I've got an IExternalCommand wich simply put a TextNote into a view and it works when I run it with the AIM.
But, I've got an other IExternalCommand wich call a method coded into IExternalApplication with make a Show of a window form.
And, in this case, it does'nt work.
Do you know why?

**Comment by chuongmep** [comment]
@pierrenavarra  can show some code demo ?

**Comment by chuongmep** [comment]
> 
Hmm, AIM just execute command inside Execute this : 
```cs
public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
    {
        //do something not starup IExternalApplication 
        return Result.Succeeded;
    }
```
Reson error because AIM not startup **IExternalApplication**, IExternalApplication only load when you define .addin, so thisApp will be null now => not working.

**Comment by pierrenavarra** [comment]
Yes!!! It works!!
Many thx @chuongmep !!

**Comment by chuongmep** [comment]
@pierrenavarra let ensure that you have copied enough all library to folder add-in ?

**Comment by pierrenavarra** [comment]
I've got only one dll

**Comment by chuongmep** [comment]
let check
![image](https://user-images.githubusercontent.com/31106432/186696487-ef905230-4bda-49e9-8d6b-3d4cb819c00b.png)

**Comment by chuongmep** [comment]
it work in my computer
https://user-images.githubusercontent.com/31106432/186697741-c40292ea-cb09-4713-a35a-30ad70ef5d8f.mp4

**Comment by pierrenavarra** [comment]
it works when you click on btn and next on running command via AIM?
What XCedd.WPF.AvaonDock.dll is?

**Comment by chuongmep** [comment]
> 
@pierrenavarra Addinmanager can't load a assembly duplicate because we can't unload assembly before, with define .addin in revit, just have way to unload addin is close revit because revit still is in .NET Framework 4.8.
https://stackoverflow.com/questions/6258160/unloading-the-assembly-loaded-with-assembly-loadfrom

**Comment by pierrenavarra** [comment]
Oh I see and is your link is a solution or not?

**Comment by chuongmep** [comment]
@pierrenavarra it is bad solution, may be needing Autodesk update Revit support .NET Core or NET6 to develop future unload assembly
https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability

**Comment by pierrenavarra** [comment]
Ok, I understand. Anyway, AIM works and permits me to debug trace my code and it's cool!
Many thx!

**Comment by pierrenavarra** [comment]
Hi @chuongmep 
I still have a pb .
Because I'm raising a DocumentClosing event on IExternalApplication...

**Comment by pierrenavarra** [comment]
Ok, I finded and call my Event on IExternalCommand..Sorry for disturbing
