### ISSUE TITLE
Is it possible to Run command into AIM via ShortCut?

### ISSUE THREAD

**Issue by pierrenavarra** [chuongmep/RevitAddInManager#31]
Hi @chuongmep 
Is it possible to Run a command via AIM with a ShortCut?

**Comment by chuongmep** [comment]
you can do it 
![image](https://user-images.githubusercontent.com/31106432/186843564-d936d460-b83a-494c-97da-1e2c484a611a.png)

**Comment by pierrenavarra** [comment]
Hy @chuongmep 
Ok, that's cool, but, no way to add ShortCut to a specific command loaded in AIM?
![screenshot_200](https://user-images.githubusercontent.com/54843266/186844138-8b8535b2-6e63-4114-a747-2d73b3ba3e4d.png)

**Comment by chuongmep** [comment]
@pierrenavarra why you don't use **add-in manager faceless** feature, it run command nearest ?

**Comment by pierrenavarra** [comment]
> why you don't use **add-in manager faceless** feature, it run command nearest ?

Euh...what do you mean?

**Comment by chuongmep** [comment]
why you don't use faceless in case need run a last command ? 
![image](https://user-images.githubusercontent.com/31106432/186846240-be7f1cd8-4f21-4c84-bb59-ab9176d7d6e5.png)

**Comment by pierrenavarra** [comment]
Excellent!!!! In this mode, it runs last selected command done in ManualMode, is it?

**Comment by chuongmep** [comment]
@pierrenavarra correct

**Comment by chuongmep** [comment]
Please read wiki to know more info https://github.com/chuongmep/RevitAddInManager/wiki/How-To-Use-Add-In-Manager

**Comment by pierrenavarra** [comment]
> Please read wiki to know more info https://github.com/chuongmep/RevitAddInManager/wiki/How-To-Use-Add-In-Manager

Excellent!! Many thx again
