### ISSUE TITLE
Debug/Trace shows no output

### ISSUE THREAD

**Issue by sigtrygg-space** [chuongmep/RevitAddInManager#32]
**Describe the bug**
First of all, thank you for this great piece of software, it helps _a lot_!
Today, I wanted to test the Trace/Debug feature, which would be so very useful - but sadly it did not work...
For testing i copied your _ColorWriteLine_ command (see screenshot) and it ran without any errors.
After running the command though, neither Listener-window nor Debug/Trace Output Dockpanel had any content.
Is there anything else I might be missing? Any idea as to why it won't log anything?

**Expected behavior**
As per my understanding, there should be 5 colored lines of text put out on the Debug/Trace Output and the Listener-window.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/531677/186908925-f5da0ba2-2826-4e4a-84d8-306f7f10897e.JPG)

**Desktop (please complete the following information):**
OS: Windows 10 Pro
Revit-Version: 2023.0 (23.0.11.19)
AddInManager-Version: 1.3.5 (the latest version as of today => [https://github.com/chuongmep/RevitAddInManager/releases/latest](https://github.com/chuongmep/RevitAddInManager/releases/latest))
.NET-Version of my AddIn: 4.8

**Comment by chuongmep** [comment]
@sigtrygg-space  Try test again, if still not working, please upload project to GitHub, I will help review .

**Comment by sigtrygg-space** [comment]
I'll repair/reinstall the addin, copy your original Test.cs file to my project and try again from there on Monday. 

Are there any known sources for an error like this? Any other addins that might pose a problem? Or maybe anything missing in my code? I'd really love to have this functionality

**Comment by chuongmep** [comment]
@sigtrygg-space I don't see any error in code, may be need check some config of project from your setting or check agian your computer.

**Comment by chuongmep** [comment]
Nice, happy coding.
