### ISSUE TITLE
Clearing Debug.trace output with code?

### ISSUE THREAD

**Issue by pierrenavarra** [chuongmep/RevitAddInManager#33]
Hi @chuongmep 
Hope you fill good.
Is it possible to clear the Debug.Trace output by codding?

**Comment by chuongmep** [comment]
If you want do it, please remove this file because it contains all log recorded.
![image](https://user-images.githubusercontent.com/31106432/187225873-e08dee12-3fb1-492e-a38b-a0dc7b716356.png)

**Comment by pierrenavarra** [comment]
All right, thx!
