### ISSUE TITLE
Nothing appears in Debug/Trace dockable 

### ISSUE THREAD

**Issue by pierrenavarra** [chuongmep/RevitAddInManager#35]
Hi @chuongmep 
The dockable panel Debug/Trace Event do not show nothing whereas txt file is not empty. Do you know what?
I've noticed that the Listener tab into Revit Add in Manager form works and display what the txt file content. But not the panel...
I've allready clear all the AddIn directory but does not work..
Thx for help.

**Comment by chuongmep** [comment]
@pierrenavarra Let try update latest version.I guess it same with issues report from #32

**Comment by pierrenavarra** [comment]
Hop, it works, thx @chuongmep

**Comment by chuongmep** [comment]
> Hop, it works, thx @chuongmep
@pierrenavarra it working ?
