### ISSUE TITLE
Clearing Dockable Debug/Trace output 

### ISSUE THREAD

**Issue by pierrenavarra** [chuongmep/RevitAddInManager#36]
Hi @chuongmep 
It could be nice to be able to Clear the Dockable Debug panel by codding.
You recomanded me to clear the txt file , ok but, when I do this , DockAble panel still with lines... Even if I close A re-open it.

Working if I close Revit but, it could be nice while Revit is in..

PS : I've noticed that I have to Remove App first if I I Want that the Debug.Trace Events works

**Comment by chuongmep** [comment]
@pierrenavarra sorry I reply late, it ok if you have any pull request , I will review. At the moment, I see it don't see any useful when create this feature , please provide more reason why you want, while button clear is enough ?

**Comment by pierrenavarra** [comment]
@chuongmep 
Thx answering
You're right, Clear button is enough, evrything is oki!
Have a nice Week-end
