### ISSUE TITLE
Cannot load .dll from an external source

### ISSUE THREAD

**Issue by aryanfaghihi** [chuongmep/RevitAddInManager#40]
I use Parallels to develop for Revit and I store my projects on my Mac partition (`\\MAC\...`). Loading compiled files from the MAC partition results in 

System.NullRerefenceException as shown in the picture below
<img width="521" alt="image" src="https://user-images.githubusercontent.com/4688602/194212456-bd41e8d8-5260-4523-812d-177c7c7dae51.png">

**To Reproduce**
1. Create a Visual Studio project and store it in your MAC partition
2. Compile the projec 
3. Load the `.dll` files from the MAC parition 

**Expected behavior**
This should work or at least give a reasonable error so it is easier to debug. 

It took me a very long time to figure this out. Part of the reason I'm leaving this here is to help others facing similar issues.

**Comment by chuongmep** [comment]
Hi @aryanfaghihi,
At the moment I don't have macos to check help you, do you can try use debug in debug mode project?

**Comment by aryanfaghihi** [comment]
Sure, I'll give it a go when I get some free time

**Comment by chuongmep** [comment]
@aryanfaghihi I just guess virtual computer have way mapping and save by another way, path will be come relative path.

**Comment by chuongmep** [comment]
Fixed in next version
<img width="1548" alt="image" src="https://user-images.githubusercontent.com/31106432/208250763-5acf5b96-c16e-446f-a2fb-36e3404d55d6.png">
