### ISSUE TITLE
Chuongmep.Revit.Api.RevitAPI - 2024.0.0.* version

### ISSUE THREAD

**Issue by NeVeSpl** [chuongmep/RevitAddInManager#42]
I saw that you published Revit 2024 api binaries on nuget. Revit 2024 right now is under NDA, are you sure that Autodesk will not mind making public something that is protected by NDA  :P?

**Comment by chuongmep** [comment]
@NeVeSpl many thanks for your reminder, but it just is first release of Revit 2024 beta, I thinked NuGet not effect more about DNA because this add-in need for now. Do you have issue like that before ?
