### ISSUE TITLE
Window Stuck Off Screen

### ISSUE THREAD

**Issue by DanKayeEvolveLab** [chuongmep/RevitAddInManager#43]
**Describe the bug**
When using multiple monitors, the Add-In manager window was appearing on a different window than my Revit Instance, probably because I moved one of the windows between monitors.

I'm currently traveling, and have only my laptop - no external monitors. When I open the Add-In Manager Window, it seems to appear offscreen on a different 'monitor' window, even though I don't have another monitor open. I can't seem to use any of the shortcuts I know to get it to move back to the one screen I currently have, so I can't really use it.

**To Reproduce**
1. On a laptop connected to a second monitor...
2. Open Revit and then open Add-In Manager Window
3. Move Add-In Manager to Second monitor, keep Revit on main Laptop monitor
4. Close Revit and Add-In Manager. Disconnected external monitor.
5. Restart Revit on just the laptop, try to oppen Add-In Manager from Ribbon.
6. Note that in taskbar, you can see the Add-In manager is open, BUT you cannot move it to the main laptop screen.

**Expected behavior**
Be able to use the shortcut 'start button' + 'arrow keys' to move Add-In manager to a visible monitor, OR simply have Add-In reset it's starting position if it would appear on an 'phantom' monitor.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by chuongmep** [comment]
Many thanks  @DanKayeEvolveLab reported , it will be fix in next version now.
