### ISSUE TITLE
Failing to load in Revit 2020

### ISSUE THREAD

**Issue by MikeM615** [chuongmep/RevitAddInManager#48]
**Describe the bug**
Recently I have been unable to use the Add-In Manager in Revit 2020, works perfectly in other years but not 2020, happens when I click any button except Show/Hide Panel, this one loads fine. 

**To Reproduce**
Open Revit 2020, click the button, or from the drop down select any item from list, Revit Blinks like it is trying to open, but then nothing shows up.

**Expected behavior**
The usual Dialog to open 

**Screenshots**
![image](https://github.com/chuongmep/RevitAddInManager/assets/78007327/91acdb01-9848-40b7-812c-fcbc6c8d0f55)

**Desktop (please complete the following information):**
![image](https://github.com/chuongmep/RevitAddInManager/assets/78007327/a27a7196-7d70-4686-9394-fa41a34795d7)
![image](https://github.com/chuongmep/RevitAddInManager/assets/78007327/c2f29d32-91c6-413b-92d6-679092352550)

**Additional context**
I have uninstalled. reinstalled and repaired to no avail. 

Not priority I can still work in a newer version, I just have all my baseline stuff in 2020 still so its just my normal oldest version I do my baseline testing in.

**Comment by chuongmep** [comment]
Hi @MikeM615 , many thank for your report, did you tried debug with add-in manager yet ?

**Comment by MikeM615** [comment]
Hi @chuongmep I did not, assuming though because the UI isn't loading though is why I cannot find the option. attached a quick video showing what I am seeing. 
[Video 5-19 at 11.27.webm](https://github.com/chuongmep/RevitAddInManager/assets/78007327/b2c9cd94-e24c-4bd3-8f24-f937105875da)

**Comment by chuongmep** [comment]
Hi @MikeM615, you can try clone this github repo and try debug with your computer. After I check from my side, I can't create this problem, could you try debug with repo ver 2020 ?

**Comment by chuongmep** [comment]
After test with version 2020, I can't see any problem like you reported, this is some recommend you can follow to resolve : 
- Uninstall some add-in conflict 
- Check problem with another add-in 
- Check your monitor (Maybe you are using dual screen ?)
If this is problem still cause, please open again topic to discuss, Regard.
