### ISSUE TITLE
Error exited with code 1

### ISSUE THREAD

**Issue by fobmasta** [chuongmep/RevitAddInManager#49]
I'm new to this so please excuse me if my question is basic. Here's the issue I'm having:
I open Revit 2024 and use the AIM to load a command. Then back in VS, I make some changes to the code. I click "Build Solution" and get the following error:
The command "copy "C:\Users\user\source\repos\MyRevitCommands\MyRevitCommands\bin\Debug\"."" "C:\Users\user\AppData\Roaming\Autodesk\Revit\Addins\2024\"" exited with code 1.	MyRevitCommands	

This error disappears if I build it after I close Revit.
Any help would be appreciated!

Edit: Sorry I figured out the solution. I had copy"$(TargetDir)"."""$(AppData)\Autodesk\Revit\Addins\2024\ in my post-build event command line, which I think was causing the issue. I deleted and it's all good.

**Comment by chuongmep** [comment]
Hi @fobmasta, please set your configuration is 2024, tune off revit and try rebuild solution of project.
Regards.
