### ISSUE TITLE
Windows doesn't shown

### ISSUE THREAD

**Issue by MohamedIbrahimPA** [chuongmep/RevitAddInManager#55]
After installing and try to run dlls, the orders (Add-In Manager(Manual Mode)), (Add-In Manager(Manual Mode, Faceless)) and (Add-In Manager(Read Only Mode)) don't be shown, the windows don't appear. 

![image](https://github.com/chuongmep/RevitAddInManager/assets/170517880/48ede317-9217-4ba2-a1ba-a6175b70b66a)

**Comment by chuongmep** [comment]
Hi @MohamedIbrahimPA , did you open two screen mode ? it is problem happend and fixed  at #43

**Comment by chuongmep** [comment]
The problem without anwser will be close after two week, so if the problem still happend, please let's me know to reopen, thank you.

**Comment by angiepalen** [comment]
I am also currently experiencing this issue after I used the attached to process in debug function in Visual Studio. I'm using Revit 2025.

**Comment by angiepalen** [comment]
@leomalyshev It worked! Thank you so much!

**Comment by chuongmep** [comment]
Great !  Thank you @leomalyshev
