### ISSUE TITLE
Missing WinRT.Runtime after changing TargetFramework

### ISSUE THREAD

**Issue by sgrodnik** [chuongmep/RevitAddInManager#58]
**Describe the bug**
When running the command through Addin Manager, a System.TypeInitializationException error occurs due to a missing WinRT.Runtime library. The error occurs if I compile for r25, but not if I compile for r23 and run in r25. It worked, but then I narrowed down TargetFramework in my csproj to support Windows.UI.Notifications with CommunityToolkit.WinUI.Notifications package. 

**To Reproduce**
1. Run the command via Addin Manager.
2. The error appears immediately upon execution.

**Expected behavior**
The command should execute without any errors

**Screenshots**
Error
![image](https://github.com/user-attachments/assets/5376c513-4679-4ca8-a94a-486f8280ed88)

My breaking change
![image](https://github.com/user-attachments/assets/565cfd34-ef6f-4c98-8911-5b0c62c0f8b6)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 11 Enterprise, Version 10.0.26100 N/A Build 26100
 - Version 1.5.6, Revit 2025.1

**Additional context**
```
System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'WinRT.Runtime, Version=2.1.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709'. The system cannot find the file specified.
File name: 'WinRT.Runtime, Version=2.1.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709'
   at WinRT.BimToolsR25GenericHelpers.GlobalVtableLookup.InitializeGlobalVtableLookup()
   at .cctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.GetActivationInfo(ObjectHandleOnStack pRuntimeType, * ppfnAllocator, Void** pvAllocatorFirstArg, * ppfnCtor, BOOL* pfCtorIsPublic)
   at System.RuntimeType.ActivatorCache..ctor(RuntimeType rt)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at RevitAddinManager.Command.AddinManagerBase.RunActiveCommand(ExternalCommandData data, String& message, ElementSet elements)
```

**Comment by chuongmep** [comment]
Hi @sgrodnik, thank you for your report issue , did you check in bin folder your files assembly loaded, `WinRT.Runtime` need make sure is include together with bin folder output.

**Comment by sgrodnik** [comment]
Hi @chuongmep, thank you for your great work and for helping here.
The file is not in my bin folder, and I am not using this library. I thought it was yours.

**Comment by sgrodnik** [comment]
The issue was resolved by manually adding the file, thanks. It seems to be some kind of dependency of a dependency? I don’t understand why it isn’t being copied to the bin folder automatically during the build. 
Thank you! Have a great day!

**Comment by chuongmep** [comment]
Hi @sgrodnik , just for more information, sometime if the dependencies is too deep level to scan,  the addin manager not able to load it becuase it effect how your nuget package load into project and build it. 
Regard.
