### ISSUE TITLE
Revit encountered a The component does have a resource identified by the uri

### ISSUE THREAD

**Issue by chuongmep** [chuongmep/RevitAddInManager#6]
**Describe the bug**
Revit encountered a The component does have a resource identified by the uri
Post Relate : https://stackoverflow.com/questions/1453107/how-to-force-wpf-to-use-resource-uris-that-use-assembly-strong-name-argh/26689750#26689750
**To Reproduce**
1. Load Add-in (Allway Load)
2. Open Addin Manager(Loaded)
3. Load new Add-in manager duplicate assembly
4. Open again Add-in Manager(Loaded)
5. See Error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/31106432/150844427-35d07bf3-0e84-43d6-86db-98775847dde8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 20H3
 - Revit : 2023

**Comment by chuongmep** [comment]
Resolved in version [22.0.0.5](https://github.com/chuongmep/RevitAddInManager/releases/tag/2022.0.0.5)

**Comment by Cazorlas** [comment]
Chào anh, em có làm 1 tool add-in revit bằng C#, thì chạy bằng externalCommand thì rất ổn, tuy nhiên khi em đóng gói thành ribbon và chạy thử. Ban đầu nó vẫn hoạt động tốt, nhưng đc 1 thời gian, nó bị lỗi như anh đề cập ở trên, tức lá báo thiếu file XAML của add-in đó. Em có thử 1 số cách như kiểm tra namspace của XAML hay Build XAML dưới dạng Page nhưng vẫn ko khắc phục được. Anh có gặp trường hợp này chưa anh.

**Comment by chuongmep** [comment]
Chào em, em đã kiểm tra qua các dependencies chưa, nếu thiếu thì hãy thêm một số dependencies phụ thuộc đi kèm vào sẽ không vấn đề gì. Trong trường hợp xung đột tại chỗ với các add-in đã tải em cần đóng gói add-in của em lại như một Merge Assembly.

**Comment by Cazorlas** [comment]
Dạ em có xử lý được rồi, em kiểm tra dependencies và đảm bảo đầy đủ, build thành PAGE. Vấn đề của em nằm ở hàm:

`InitializeComponent();`

Nó tự load cái XAML vào nhưng ko hiểu sao khi em build ribbon thì chạy 1 thời gian nó lại ko hiểu. Nên em làm 1 hàm lấy Uri thủ công rồi gọi nó thay cho InitializeComponent();. Hàm thì em làm theo cái link anh gửi ở khúc trên:

`public static void LoadXaml(object obj)
{
    if (obj == null) throw new ArgumentNullException(nameof(obj));

    Type type = obj.GetType();
    AssemblyName assemblyName = type.Assembly.GetName();
    string asmName = assemblyName.Name;

    // Loại bỏ phần tên Assembly khỏi namespace (ví dụ: PaperMEP.UI_Templates → UI_Templates)
    string relativeNamespace = type.Namespace.StartsWith(asmName + ".")
        ? type.Namespace.Substring(asmName.Length + 1)
        : type.Namespace;

    // Chuyển thành đường dẫn: UI_Templates → UI_Templates/, Split_Ducts.UI → Split_Ducts/UI/
    string folderPath = relativeNamespace.Replace('.', '/');

    // Xây dựng URI đầy đủ
    string uriString = string.Format("/{0};component/{1}/{2}.xaml",
        asmName,
        folderPath,
        type.Name);

    Uri uri = new Uri(uriString, UriKind.Relative);

    // Load XAML vào đối tượng
    Application.LoadComponent(obj, uri);
}`
